---
- hosts: docker
  tasks:
      - name: install utils
        yum:
            name: yum-utils
            state: latest
            
      # - name: register docker repository
#         yum_repository:
#             name: docker
#             baseurl: https://download.docker.com/linux/centos/docker-ce.repo
            
      - name: register docker repository
        command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
        
      - name: update yum cache
        command: yum makecache fast
        
      - name: install docker
        yum:
            name: docker-ce
            state: latest
            
      - name: start docker daemon
        command: systemctl start docker